// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Db;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(UtronDbContext))]
    partial class UtronDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.ParkingRecord", b =>
                {
                    b.Property<string>("LicensePlateID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LotNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParkingDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LicensePlateID");

                    b.ToTable("ParkingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
